### ISSUE TITLE
checkout not loading

### ISSUE THREAD

**Issue by tobiasolge** [schrammel-codes/magento2-epc-qr-code#1] opened 2024-07-17 07:29 UTC
in version 2.4.6-p6 checkout is not loading for me.
I cannot see any exceptions in the log.

**Comment by aschrammel** [comment] 2024-08-10 16:32
Hi @tobiasolge 

Thanks for your report.

I'm not able reproduce the issue on a Magento 2.4.6-p6 vanilla installation.
Could you please retry on a vanilla instance and report if your issue persists?

**Comment by aschrammel** [comment] 2024-09-05 12:07
Going to close this due to missing feedback.

**Closed as completed by aschrammel** 2024-09-05 12:07 UTC
Labels: not reproducible
